Restore pdmysql parallel job
Percona-Lab/jenkins-pipelines pull request #1204
Opened 2021-09-15 08:14 UTC by mu-samoylov

2021-09-16 07:50 UTC, EvgeniyPatlan approved these changes

2021-09-16 10:26 UTC, EvgeniyPatlan requested changes
please add jira ticket into commit description

2023-05-17 09:13 UTC, EvgeniyPatlan requested changes
please add jira ticket into commit description

2024-01-26 15:58 UTC, vyarosh commented
I assume that is no-one need these changes for 3 years we may close it.

2024-01-26 15:58 UTC, closed without merging