PMM-7 migrate client build job to new farm
Percona-Lab/jenkins-pipelines pull request #1367
Opened 2022-01-03 15:10 UTC by nikita-b

2022-01-06 11:22 UTC, atymchuk requested changes

2022-01-06 11:22 UTC, atymchuk commented on pmm/pmm2-client-autobuild.groovy
> +                        docker login -u "${USER}" -p "${PASS}"
we'd better use `--password-stdin` as recommended by docker docs.

2022-01-06 11:22 UTC, atymchuk commented on pmm/pmm2-client-autobuild.groovy
> +                        docker login -u "${USER}" -p "${PASS}"
```suggestion
                        echo "${PASS}" | docker login -u "${USER}" --password-stdin
```

2022-01-06 11:22 UTC, atymchuk commented on pmm/pmm2-client-autobuild.groovy
> +                    ./build/bin/build-client-rpm centos:8
Still not dropping centos:8?

2022-01-31 19:22 UTC, nikita-b commented on pmm/pmm2-client-autobuild.groovy
> +                    ./build/bin/build-client-rpm centos:8
We can't drop it, because of RHEL 8 :(

2022-02-01 08:25 UTC, atymchuk approved these changes

2022-02-01 09:24 UTC, merged