K8 spsmdb 704 add azure
Percona-Lab/jenkins-pipelines pull request #1665
Opened 2022-07-26 09:19 UTC by nmarukovich

2022-07-28 16:32 UTC, tplavcic requested changes

2022-07-28 16:32 UTC, tplavcic commented on cloud/jenkins/psmdb_operator_aks_version.groovy
> +                    gcloud components update kubectl
Do we need whole google-cloud-sdk, if we only use kubectl maybe we can just download that binary?

2022-07-28 16:32 UTC, tplavcic commented on cloud/jenkins/psmdb_operator_aks_latest.groovy
> +                    gcloud components update kubectl
Do we need whole google-cloud-sdk, if we only use kubectl maybe we can just download that binary?

2022-07-29 08:48 UTC, tplavcic requested changes

2022-07-29 08:48 UTC, tplavcic commented on cloud/jenkins/psmdb-operator-aks-latest.yml
> +        description: PMM image
Please add IMAGE_PMM_SERVER_REPO and IMAGE_PMM_SERVER_TAG options.

2022-07-29 08:48 UTC, tplavcic commented on cloud/jenkins/psmdb-operator-aks-version.yml
> +
Please add IMAGE_PMM_SERVER_REPO and IMAGE_PMM_SERVER_TAG options.

2022-07-29 08:48 UTC, tplavcic commented on cloud/jenkins/psmdb_operator_aks_latest.groovy
> +                        fi
Please add IMAGE_PMM_SERVER_REPO and IMAGE_PMM_SERVER_TAG options.

2022-07-29 08:48 UTC, tplavcic commented on cloud/jenkins/psmdb_operator_aks_latest.groovy
> +            name: 'IMAGE_PMM')
Please add IMAGE_PMM_SERVER_REPO and IMAGE_PMM_SERVER_TAG options.

2022-07-29 08:48 UTC, tplavcic commented on cloud/jenkins/psmdb_operator_aks_version.groovy
> +                        fi
Please add IMAGE_PMM_SERVER_REPO and IMAGE_PMM_SERVER_TAG options.

2022-07-29 08:48 UTC, tplavcic commented on cloud/jenkins/psmdb_operator_aks_version.groovy
>              name: 'IMAGE_PMM')
Please add IMAGE_PMM_SERVER_REPO and IMAGE_PMM_SERVER_TAG options.

2022-07-29 08:48 UTC, tplavcic commented on cloud/jenkins/pxc-operator-aws-openshift.yml
> -
Please delete the groovy file and jenkins job also.

2022-07-29 08:48 UTC, tplavcic commented on cloud/jenkins/psmdb-operator-aws-openshift.yml
> -
Please delete the groovy file and jenkins job also.

2022-07-29 09:05 UTC, tplavcic requested changes

2022-07-29 09:05 UTC, tplavcic commented on cloud/jenkins/psmdb_operator_aks_latest.groovy
> +                        export IMAGE_PMM_SERVER_REPO=${IMAGE_PMM_SERVER_REPO}
Alignment

2022-07-29 09:05 UTC, tplavcic commented on cloud/jenkins/psmdb_operator_aks_version.groovy
> +                        export IMAGE_PMM_SERVER_REPO=${IMAGE_PMM_SERVER_REPO}
Alignment

2022-07-29 09:05 UTC, tplavcic commented on cloud/jenkins/pxc_operator_aws_openshift.groovy
> -void IsRunTestsInClusterWide() {
Please delete the groovy file for PSMDB also.

2022-07-29 09:08 UTC, tplavcic commented on cloud/jenkins/psmdb-operator-aks-latest.yml
> +        description: PMM image
re-check please, I don't see variables here

2022-07-29 09:09 UTC, tplavcic commented on cloud/jenkins/psmdb-operator-aks-version.yml
> +
re-check please, I don't see variables here

2022-07-29 09:12 UTC, nmarukovich commented on cloud/jenkins/psmdb-operator-aks-latest.yml
> +        description: PMM server image tag
@tplavcic

2022-07-29 11:06 UTC, tplavcic approved these changes

2022-07-29 12:12 UTC, merged