Fix permissions for pmm-user
Percona-Lab/jenkins-pipelines pull request #1738
Opened 2022-09-01 10:56 UTC by VoK0

* run pmm-agent as a root user

2022-09-15 20:29 UTC, atymchuk requested changes

2022-09-15 20:29 UTC, atymchuk commented on pmm/aws-staging-start.groovy
> +                    sh"sudo sed -i -e '/secure_path/ s[=.*[&:/usr/local/home/ec2-user/workspace/aws-staging-start/pmm2-client/config:/usr/local/percona/pmm2/bin:/usr/local/percona/pmm2/config[' /etc/
Why do we need this?

2022-09-15 20:29 UTC, atymchuk commented on vars/setupPMMClient.groovy
> +                          sudo pmm-agent setup --config-file=`pwd`/pmm2-client/config/pmm-agent.yaml --server-address=\$SERVER_IP:443 --server-insecure-tls --server-username=admin --server-password=\
The official [docs](https://docs.percona.com/percona-monitoring-and-management/setting-up/client/index.html#register) do not say it need to be run with sudo, do they?

2022-09-16 05:13 UTC, puneet0191 commented
outdated PR, forgot to close

2022-09-16 05:13 UTC, closed without merging