ENG-7 update pmm jenkins key list
Percona-Lab/jenkins-pipelines pull request #1764
Opened 2022-09-21 12:32 UTC by vorsel

2022-09-21 12:32 UTC, EvgeniyPatlan approved these changes

2022-09-27 16:35 UTC, atymchuk commented
@EvgeniyPatlan I don't think we follow the least privilege principle here. What does adding more people to PMM Jenkins solve?

2022-09-30 17:01 UTC, atymchuk requested changes
Let's close this one as we have enough people on the list.

2022-10-08 22:41 UTC, atymchuk commented
Closing this as redundant.

2022-10-08 22:41 UTC, closed without merging