ENG-1152 pmm jenkins: access for @svinasi
Percona-Lab/jenkins-pipelines pull request #1782
Opened 2022-09-27 07:57 UTC by vorsel

2022-09-27 08:12 UTC, EvgeniyPatlan approved these changes

2022-09-27 16:29 UTC, atymchuk requested changes

2022-09-27 16:29 UTC, atymchuk commented on IaC/pmm.cd/init.groovy.d/matrix.groovy
> +        'svinasi': ['Overall Read','Agent Build','Agent Configure','Agent Connect','Agent Create','Agent Delete','Agent Disconnect','Job Build','Job Cancel','Job Configure','Job Create','Job Delete',
We do not favour granting individual permissions to employees unless absolutely necessary. Please add `svinasi` to the `pmm-devs` group on github. This is much faster and and does not require a PR.

2022-09-28 08:07 UTC, atymchuk commented
Stefan confirmed he got access to Jenkins, so I'm closing this.

2022-09-28 08:07 UTC, closed without merging