PMM-10849 playwright cli
Percona-Lab/jenkins-pipelines pull request #1796
Opened 2022-10-07 23:24 UTC by atymchuk

2022-10-10 08:21 UTC, EvgeniyPatlan requested changes

2022-10-10 08:21 UTC, EvgeniyPatlan commented on pmm/aws-staging-start.groovy
> +                        sudo yum -y install https://repo.percona.com/yum/percona-release-1.0-27.noarch.rpm
it is better to just use latest version of percona-release https://repo.percona.com/yum/percona-release-latest.noarch.rpm

2022-10-21 23:31 UTC, vyarosh approved these changes
Looks good to me!

2022-10-21 23:32 UTC, vyarosh approved these changes

2022-10-22 09:05 UTC, merged