PS-8481: Add OL9 and ubuntu-jammy in InnoDB cluster Job
Percona-Lab/jenkins-pipelines pull request #1865
Opened 2022-11-12 11:54 UTC by kaushikpuneet07

2022-11-14 10:31 UTC, eleo007 requested changes

2022-11-14 10:31 UTC, eleo007 commented on ps/jenkins/test-ps-innodb-cluster.groovy
> +    remote: 'https://github.com/kaushikpuneet07/jenkins-pipelines.git'
revert

2022-11-14 10:31 UTC, eleo007 commented on ps/jenkins/test-ps-innodb-cluster.groovy
> +        git clone -b PS-8481 https://github.com/kaushikpuneet07/package-testing
revert

2022-11-14 10:31 UTC, eleo007 commented on ps/jenkins/test-ps-innodb-cluster.yml
> +                url: https://github.com/kaushikpuneet07/jenkins-pipelines.git
revert

2022-11-14 10:31 UTC, eleo007 commented on ps/jenkins/test-ps-innodb-cluster.yml
> +                    - 'innodb-job'
revert

2022-11-15 18:58 UTC, kaushikpuneet07 commented on ps/jenkins/test-ps-innodb-cluster.groovy
> +    remote: 'https://github.com/kaushikpuneet07/jenkins-pipelines.git'
Fixed

2022-11-15 18:58 UTC, kaushikpuneet07 commented on ps/jenkins/test-ps-innodb-cluster.groovy
> +        git clone -b PS-8481 https://github.com/kaushikpuneet07/package-testing
Fixed

2022-11-15 18:58 UTC, kaushikpuneet07 commented on ps/jenkins/test-ps-innodb-cluster.yml
> +                url: https://github.com/kaushikpuneet07/jenkins-pipelines.git
Fixed

2022-11-15 18:59 UTC, kaushikpuneet07 commented on ps/jenkins/test-ps-innodb-cluster.yml
> +                    - 'innodb-job'
Fixed

2022-11-16 08:12 UTC, eleo007 approved these changes

2022-11-16 08:15 UTC, merged