PXC-3998: Add ubuntu:jammy and oraclelinux:9
Percona-Lab/jenkins-pipelines pull request #1880
Opened 2022-11-23 08:00 UTC by kamil-holubicki

This is adjusted install-deps script for PXC build images generation
1. ubuntu:jammy added
2. 8.0 toolset by default for ubuntu:bionic
3. oraclelinux:9 added
4. Some refactoring towards unifying images with PS in the future

Please build Docker images for ubuntu:jammy, ubuntu:bionic and oraclelinux:9 at least and upload to the repository to be able to use by Jenkins.
It would be good to rebuild all images as boos tarball has been updated. Having this we will avoid constant downloading of boost tarball.

2022-11-23 11:20 UTC, EvgeniyPatlan requested changes

2022-11-23 13:00 UTC, kamil-holubicki commented on pxc/docker/install-deps
> +wget_loop 'boost_1_77_0.tar.bz2' 'http://downloads.sourceforge.net/boost/boost/1.77.0/boost_1_77_0.tar.bz2'
The point is that we need bz2, not gz. if we download bz2, PXC cmake will trigger boost download

2022-11-23 13:02 UTC, kamil-holubicki commented on pxc/docker/install-deps
> +      PKGLIST+=" procps-ng-devel"
yup, fixed.

2022-11-24 10:04 UTC, EvgeniyPatlan approved these changes

2022-11-24 10:04 UTC, EvgeniyPatlan commented on pxc/docker/install-deps
> +wget_loop 'boost_1_77_0.tar.bz2' 'http://downloads.sourceforge.net/boost/boost/1.77.0/boost_1_77_0.tar.bz2'
:+1:

2022-11-24 10:33 UTC, merged