CLOUD-705 add labels under cluster creation
Percona-Lab/jenkins-pipelines pull request #1920
Opened 2022-12-20 08:08 UTC by nmarukovich

Signed-off-by: Natalia Marukovich <natalia.marukovich@percona.com>

2022-12-20 08:13 UTC, tplavcic approved these changes

2022-12-20 09:12 UTC, egegunes approved these changes

2022-12-20 09:15 UTC, hors approved these changes

2022-12-20 10:08 UTC, cap1984 approved these changes

2022-12-27 16:17 UTC, tplavcic requested changes

2022-12-27 16:17 UTC, tplavcic commented on cloud/jenkins/pxc_operator_gke_latest.groovy
> +                gcloud alpha container clusters create --release-channel rapid $CLUSTER_NAME-${CLUSTER_SUFFIX} --cluster-version ${params.PLATFORM_VER} --zone $GKERegion --project $GCP_PROJECT --pree
Please update: `--cluster-ipv4-cidr=/21`

2022-12-27 16:17 UTC, tplavcic commented on cloud/jenkins/pxc_operator_gke_version.groovy
> +                gcloud container clusters create --zone $GKERegion $CLUSTER_NAME-${CLUSTER_PREFIX} --cluster-version $PLATFORM_VER --machine-type n1-standard-4 --preemptible --num-nodes=\$NODES_NUM -
Please update: `--cluster-ipv4-cidr=/21`.

2022-12-27 16:17 UTC, tplavcic commented on cloud/jenkins/pgo_operator_gke_latest.groovy
> +                gcloud alpha container clusters create --release-channel rapid $CLUSTER_NAME-${CLUSTER_SUFFIX} --zone ${GKERegion} --cluster-version $GKE_VERSION --project $GCP_PROJECT --preemptible
Please add `--cluster-ipv4-cidr=/21`.

2022-12-27 16:17 UTC, tplavcic commented on cloud/jenkins/pgo_operator_gke_version.groovy
> +                gcloud container clusters create --zone ${GKERegion} \$(echo $CLUSTER_NAME-${CLUSTER_PREFIX} | cut -c-40) --cluster-version $GKE_VERSION --machine-type n1-standard-4 --preemptible --n
Please add `--cluster-ipv4-cidr=/21`.

2022-12-27 16:17 UTC, tplavcic commented on cloud/jenkins/ps_operator_gke_version.groovy
> +                gcloud container clusters create --zone $GKERegion $CLUSTER_NAME-${CLUSTER_SUFFIX} --cluster-version $PLATFORM_VER --machine-type n1-standard-4 --preemptible --num-nodes=\$NODES_NUM -
Please add `--cluster-ipv4-cidr=/21`.

2022-12-27 16:17 UTC, tplavcic commented on cloud/jenkins/psmdb_operator_gke_latest.groovy
> +                gcloud alpha container clusters create --release-channel rapid $CLUSTER_NAME-${CLUSTER_SUFFIX} --zone $GKERegion --cluster-version $PLATFORM_VER --project $GCP_PROJECT --preemptible -
Please add `--cluster-ipv4-cidr=/21`.

2022-12-27 16:17 UTC, tplavcic commented on cloud/jenkins/psmdb_operator_gke_version.groovy
> +                gcloud container clusters create --zone $GKERegion $CLUSTER_NAME-${CLUSTER_PREFIX} --cluster-version $PLATFORM_VER --machine-type n1-standard-4 --preemptible --num-nodes=3 --network=j
Please add `--cluster-ipv4-cidr=/21`.

2023-01-04 10:36 UTC, tplavcic approved these changes

2023-01-04 10:41 UTC, merged