K8SPG-286 Run test in parallel on openshift
Percona-Lab/jenkins-pipelines pull request #2036
Opened 2023-03-24 13:48 UTC by cap1984

Thanks to @nmarukovich for the path provided

2023-03-27 06:51 UTC, tplavcic approved these changes

2023-03-27 06:52 UTC, tplavcic requested changes

2023-03-27 06:52 UTC, tplavcic commented on cloud/jenkins/pgo_operator_aws_openshift-4.groovy
> +                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'openshift-cicd'], file(credentialsId: 'aws-openshift-41-key-pu
Why `psmdb-openshift-secret-file`?

2023-03-28 06:54 UTC, cap1984 commented on cloud/jenkins/pgo_operator_aws_openshift-4.groovy
> +                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'openshift-cicd'], file(credentialsId: 'aws-openshift-41-key-pu
human error. fixed

2023-03-28 06:55 UTC, tplavcic approved these changes

2023-03-28 06:57 UTC, nmarukovich approved these changes

2023-03-28 06:57 UTC, merged