Make pxb package-testing job working using groovy file.
Percona-Lab/jenkins-pipelines pull request #2212
Opened 2023-07-17 15:58 UTC by panchal-yash

2023-07-18 08:12 UTC, eleo007 requested changes

2023-07-18 12:51 UTC, panchal-yash commented on pxb/jenkins/pxb-package-testing-all.groovy
> -        string(
Hardcoded the package-testing repo cloinging in the .groovy file itself.

2023-07-19 11:11 UTC, eleo007 commented on pxb/jenkins/pxb-package-testing-all.groovy
> -        string(
We use custom repo for test runs, that is why we have it in options. Could you revert the change?

2023-07-19 13:10 UTC, panchal-yash commented on pxb/jenkins/pxb-package-testing-all.groovy
> -        string(
Hi,
Reverted the change.

2023-07-20 09:11 UTC, eleo007 approved these changes

2023-07-20 10:23 UTC, merged