Add Minitests for PS 8.0 Build Job
Percona-Lab/jenkins-pipelines pull request #2335
Opened 2023-10-19 15:03 UTC by panchal-yash

* Add Minitests for PS8.0 build job.

* Minitests have only install stage for all the supported OS after the packages are built and pushed to testing repo.

* add package_tests_ps80() function for install package tests for PS_8.0 in the build job itself along with relevant notifications to the release channel (Minitests). 

* Minitest are subset of package tests, so any failure in Minitest will not trigger package-testing and integration test jobs.

2023-10-23 08:39 UTC, EvgeniyPatlan commented
I suggest reworking this in a bit different way. We can create a separate functions for running tests and installing dependencies.

I have prepared a code block but I have not tested it. Please create a test job and perform tests before merging changes


```
def installDependencies(def nodeName) {
    def aptNodes = ['min-buster-x64', 'min-bullseye-x64', 'min-bookworm-x64', 'min-bionic-x64', 'min-focal-x64', 'min-jammy-x64']
    def yumNodes = ['min-ol-8-x64', 'min-centos-7-x64', 'min-ol-9-x64', 'min-amazon-2-x64']
    
    if (aptNodes.contains(nodeName)) {
        sh '''
            sudo apt-get update
            sudo apt-get install -y ansible git wget
            ''' + (nodeName in ['min-bionic-x64', 'min-focal-x64', 'min-jammy-x64'] ? '''
            sudo apt-get install -y software-properties-common
            sudo apt-add-repository --yes --update ppa:ansible/ansible
            ''' : '')
    } else if (yumNodes.contains(nodeName)) {
        sh '''
            ''' + (nodeName == 'min-ol-8-x64' ? 'sudo yum install -y epel-release' : '') + '''
            sudo yum -y update
            sudo yum install -y ansible git wget tar
            ''' + (nodeName == 'min-amazon-2-x64' ? 'sudo amazon-linux-extras install epel' : '')
    } else {
        echo "Unexpected node name: ${nodeName}"
    }
}

def runPlaybook(def nodeName) {
    try {
        def playbook = "${ps80_install_pkg_minitests_playbook}"
        def playbook_path = "package-testing/playbooks/${playbook}"

        sh '''
            git clone --depth 1 https://github.com/Percona-QA/package-testing
        '''

        sh """
            export install_repo="\${install_repo}"
            export client_to_test="ps80"
            export check_warning="\${check_warnings}"
            export install_mysql_shell="\${install_mysql_shell}"
            ansible-playbook \
            --connection=local \
            --inventory 127.0.0.1, \
            --limit 127.0.0.1 \
            ${playbook_path}
        """
    } catch (Exception e) {
        slackNotify("${SLACKNOTIFY}", "#FF0000", "[${JOB_NAME}]: Mini Package Testing for ${nodeName} at ${BRANCH}  FAILED !!")
        error("Mini Package Tests Failed! for ${nodeName}")
    }
}

def package_tests_ps80() {
    def arrayA = [  "min-buster-x64",
                    "min-bullseye-x64",
                    "min-bookworm-x64",
                    "min-centos-7-x64",
                    "min-ol-8-x64",
                    "min-bionic-x64",
                    "min-focal-x64",
                    "min-amazon-2-x64",
                    "min-jammy-x64",
                    "min-ol-9-x64"     ]

    def stepsForParallel = [:]

    for (def nodeName : arrayA) {
        stepsForParallel[nodeName] = {
            stage("Run on ${nodeName}") {
                node(nodeName) {
                    try {
                        installDependencies(nodeName)
                    } catch (Exception e) {
                        slackNotify("${SLACKNOTIFY}", "#FF0000", "[${JOB_NAME}]: Server Provision for Mini Package Testing for ${nodeName} at ${BRANCH}  FAILED !!")
                    }
                    runPlaybook(nodeName)
                }
            }
        }
    }
    parallel stepsForParallel
}

```

2023-10-24 14:56 UTC, EvgeniyPatlan requested changes
why do you remove the existent jobs? In order to create a tests jobs you shouldn't remove prod jobs

2023-11-02 10:17 UTC, EvgeniyPatlan approved these changes

2023-11-03 13:27 UTC, eleo007 commented on ps/jenkins/percona-server-for-mysql-8.0.groovy
> +    def check_warnings = 'no'
Why do we skip warnings and shell checks?

2023-11-03 13:27 UTC, eleo007 commented on ps/jenkins/percona-server-for-mysql-8.0.groovy
>                  build job: 'package-testing-ps80', propagate: false, wait: false, parameters: [string(name: 'product_to_test', value: 'ps80'),string(name: 'install_repo', value: "testing"),string(nam
Are we going to keep triggering the job and running the same playbook in the job?

2023-11-14 13:41 UTC, eleo007 approved these changes

2023-11-14 14:14 UTC, adivinho approved these changes

2023-11-14 17:53 UTC, merged