Package Testing job for PS 8.1
Percona-Lab/jenkins-pipelines pull request #2362
Opened 2023-11-06 06:13 UTC by kaushikpuneet07

2023-11-12 19:14 UTC, EvgeniyPatlan requested changes

2023-11-12 19:14 UTC, EvgeniyPatlan commented on ps/jenkins/package-testing-ps-build-8.1.groovy
> +}
it is the same as `setup_rhel_package_tests`

2023-11-13 06:49 UTC, kaushikpuneet07 commented
Fixed review comments from evgeniy

2023-11-13 08:53 UTC, eleo007 commented on ps/jenkins/package-testing-ps-8.1.groovy
> +        job: 'package-testing-ps81-build',
Are we going to create separate jobs for every innovations releases?

2023-11-13 08:53 UTC, eleo007 commented on ps/jenkins/package-testing-ps-8.1.yml
> +        script-path: ps/jenkins/package-testing-ps-8.1.groovy
The same as above, are we going to have new jobs on every innovations release?

2023-11-13 08:53 UTC, eleo007 commented on ps/jenkins/package-testing-ps-build-8.1.groovy
> +        install: "ps_81.yml",
The same here: are we going to create/update playbooks on every innovations release?

2023-11-13 08:53 UTC, eleo007 commented on ps/jenkins/package-testing-ps-build-8.1.groovy
> +            choices: ["ps81", "client_test"],
The same as above

2023-11-13 08:53 UTC, eleo007 commented on ps/jenkins/package-testing-ps-8.1.yml
> +                - "ps81"
The same as above

2023-11-13 08:53 UTC, eleo007 commented on ps/jenkins/package-testing-ps-8.1.groovy
> +            choices: ["ps81", "client_test"],
The same as above

2023-11-23 08:46 UTC, EvgeniyPatlan approved these changes

2023-11-24 09:27 UTC, merged