Update innodb cluster job
Percona-Lab/jenkins-pipelines pull request #2444
Opened 2024-01-04 08:50 UTC by kaushikpuneet07

2024-01-08 09:34 UTC, EvgeniyPatlan requested changes

2024-01-08 09:34 UTC, EvgeniyPatlan commented on ps/jenkins/test-ps-innodb-cluster-parallel.groovy
> +library changelog: false, identifier: 'lib@innodb', retriever: modernSCM([
should be fixed before merge

2024-01-08 09:34 UTC, EvgeniyPatlan commented on ps/jenkins/test-ps-innodb-cluster-parallel.groovy
> +    remote: 'https://github.com/kaushikpuneet07/jenkins-pipelines.git'
should be fixed before merge

2024-01-08 09:34 UTC, EvgeniyPatlan commented on ps/jenkins/test-ps-innodb-cluster-parallel.yml
> +                url: https://github.com/kaushikpuneet07/jenkins-pipelines.git
should be fixed before merge

2024-01-08 09:34 UTC, EvgeniyPatlan commented on ps/jenkins/test-ps-innodb-cluster-parallel.yml
> +                    - 'innodb'
should be fixed before merge

2024-01-08 09:34 UTC, EvgeniyPatlan commented on ps/jenkins/test-ps-innodb-cluster.groovy
> +    remote: 'https://github.com/kaushikpuneet07/jenkins-pipelines.git'
should be fixed before merge

2024-01-08 09:34 UTC, EvgeniyPatlan commented on ps/jenkins/test-ps-innodb-cluster.groovy
> +        git clone https://github.com/kaushikpuneet07/package-testing.git --branch innodb
should be fixed before merge

2024-01-08 09:34 UTC, EvgeniyPatlan commented on ps/jenkins/test-ps-innodb-cluster.groovy
> +            cat  package-testing/tasks/test_prep.yml
why do we need it?

2024-01-08 09:34 UTC, EvgeniyPatlan commented on ps/jenkins/test-ps-innodb-cluster.yml
> +                url: https://github.com/kaushikpuneet07/jenkins-pipelines.git
should be fixed before merge

2024-01-08 09:34 UTC, EvgeniyPatlan commented on ps/jenkins/test-ps-innodb-cluster.yml
> +                    - 'innodb'
should be fixed before merge

2024-01-18 09:17 UTC, panchal-yash approved these changes

2024-01-26 09:54 UTC, EvgeniyPatlan approved these changes

2024-01-26 11:32 UTC, merged