Adding innovation job
Percona-Lab/jenkins-pipelines pull request #2457
Opened 2024-01-15 10:46 UTC by panchal-yash

use lts_innovation for testing

Add upgrade

Add KMS for testing..

Set Fix ansible version

Check version

replace ps80 with innovation-lts for package testing

2024-01-15 10:55 UTC, kaushikpuneet07 approved these changes
LGTM

2024-01-26 09:53 UTC, EvgeniyPatlan requested changes

2024-01-26 09:53 UTC, EvgeniyPatlan commented on ps/jenkins/package-testing-ps-build-innovation-lts.groovy
> +}
I don't see where we call this subroutine

2024-01-29 08:57 UTC, eleo007 approved these changes

2024-01-29 09:03 UTC, merged