ENG-1235 Adds "--sanitize" to MTR arguments for ASAN runs
Percona-Lab/jenkins-pipelines pull request #2582
Opened 2024-03-28 11:47 UTC by VarunNagaraju

https://perconadev.atlassian.net/browse/ENG-1235

Post-push fix. Fix string comparison for WITH_ASAN.

2024-03-28 11:58 UTC, EvgeniyPatlan requested changes

2024-03-28 11:58 UTC, EvgeniyPatlan commented on pxc/local/test-binary-pxc57
> +if [[ $WITH_ASAN == "yes" ]]; then
```suggestion
WITH_ASAN=$(echo "${WITH_ASAN}" | tr '[:upper:]' '[:lower:]')
if [[ $WITH_ASAN == "yes" ]]; then
```

2024-03-28 19:25 UTC, VarunNagaraju commented on pxc/local/test-binary-pxc57
> +if [[ $WITH_ASAN == "yes" ]]; then
Done,

2024-03-30 08:05 UTC, vorsel approved these changes

2024-03-30 08:11 UTC, merged