Automate Network endpoint group deletion
Percona-Lab/jenkins-pipelines pull request #2923
Opened 2024-10-21 17:39 UTC by nmarukovich

2024-10-25 08:08 UTC, egegunes requested changes

2024-10-25 08:08 UTC, egegunes commented on cloud/gcp-functions/cmd/orphanedNeg.go
> +					log.Printf("NEG %s is in use by a backend service.\n", neg.GetName())
log.Printf automatically adds newline, you don't need to do it

2024-10-25 08:08 UTC, egegunes commented on cloud/gcp-functions/cmd/orphanedNeg.go
> +					log.Printf("NEG %s is NOT in use, it can be deleted.\n", neg.GetName())
log.Printf automatically adds newline, you don't need to do it

2024-10-25 08:08 UTC, egegunes commented on cloud/gcp-functions/cmd/orphanedNeg.go
> +						log.Printf("Deleted unused NEG: %s, Operation: %v\n", neg.Name, op)
log.Printf automatically adds newline, you don't need to do it

2024-10-29 07:28 UTC, egegunes requested changes

2024-10-29 07:28 UTC, egegunes commented on cloud/gcp-functions/cmd/orphanedNeg.go
> +		log.Fatal("Failed to create NEG client: %v", err)
you need to use `Fatalf` not `Fatal`, otherwise `%v` won't be replaces by `err`.

2024-10-29 07:28 UTC, egegunes commented on cloud/gcp-functions/cmd/orphanedNeg.go
> +				log.Print("Checking NEG: %s\n", neg.GetName())
and you need to use `Printf` here.

log messages have newline by default, so you just need to remove `\n` at the end.

2024-10-29 09:30 UTC, egegunes approved these changes

2024-10-29 09:34 UTC, ptankov approved these changes

2024-10-29 09:35 UTC, eleo007 approved these changes

2024-10-29 10:00 UTC, merged