ENG-920: Add missing AMIs and update existing to latest versions
Percona-Lab/jenkins-pipelines pull request #556
Opened 2020-09-10 07:59 UTC by Sudokamikaze

I've installed this cloudinit at https://rel.cd.percona.com/computer/ and checked every AMI

Used official IDs from:
* Debian: https://wiki.debian.org/Cloud/AmazonEC2Image
* Ubuntu: https://cloud-images.ubuntu.com/locator/ec2/
* CentOS: https://wiki.centos.org/Cloud/AWS

2020-09-10 10:14 UTC, EvgeniyPatlan requested changes

2020-09-10 10:18 UTC, Sudokamikaze commented on IaC/rel.cd/init.groovy.d/cloud.groovy
> +imageMap['eu-west-1b.min-trusty-x64']   = imageMap['eu-west-1a.min-trusty-x64']
As it's a future release jenkins, I left them for historical/old jobs purpose, for example we have jobs which run `--build_source_deb=` on such

2020-09-10 10:18 UTC, Sudokamikaze commented on IaC/rel.cd/init.groovy.d/cloud.groovy
> +imageMap['eu-west-1b.min-jessie-x64']   = imageMap['eu-west-1a.min-jessie-x64']
I can remove it if we don't use it anymore and won't be

2020-09-10 13:22 UTC, Sudokamikaze commented on IaC/rel.cd/init.groovy.d/cloud.groovy
> +imageMap['eu-west-1b.min-trusty-x64']   = imageMap['eu-west-1a.min-trusty-x64']
Taking your side, removed 500acf5

2020-09-11 11:12 UTC, hors approved these changes

2020-09-11 12:10 UTC, EvgeniyPatlan approved these changes

2020-09-11 13:23 UTC, merged