K8SPSMDB-232: Add smart-update test
Percona-Lab/jenkins-pipelines pull request #559
Opened 2020-09-14 07:36 UTC by blez

2020-09-14 07:54 UTC, delgod requested changes
Could you please add all the new tests from the main branch in this PR?

2020-09-14 08:40 UTC, blez commented
@delgod, done

2020-09-16 11:39 UTC, hors commented on cloud/jenkins/psmdb_operator_minikube.groovy
> +                    runTest('monitoring')
Please do not add these tests for minikube. These tests do not work on minikube @cap1984  handle it.

2020-09-16 11:42 UTC, hors commented on cloud/jenkins/psmdb_operator_aws_openshift-4.groovy
> +        stage('E2E SelfHealing') {
the same for these tests , It does not work for for openshift

2020-09-16 12:22 UTC, hors approved these changes

2020-11-05 12:46 UTC, delgod approved these changes

2020-11-05 12:47 UTC, merged