ENG-906: Fix installation of git on CentOS
Percona-Lab/jenkins-pipelines pull request #561
Opened 2020-09-16 16:46 UTC by Sudokamikaze

Hrvoje reported that CentOS 8 doesn't have `git` installed:
With `|| : ` it only installs java package

Here's the sample:
```
++ sudo yum -y install java-1.8.0-openjdk git aws-cli

Last metadata expiration check: 0:00:03 ago on Wed 16 Sep 2020 04:44:46 PM UTC.
No match for argument: aws-cli
Error: Unable to find a match: aws-cli
++ :
<<>>
Dependencies resolved.
==========================================================================================
 Package                       Arch    Version                            Repo        Size
==========================================================================================
Installing:
 java-1.8.0-openjdk            x86_64  1:1.8.0.262.b10-0.el8_2            AppStream  323 k
Installing dependencies:
```

2020-09-16 16:48 UTC, EvgeniyPatlan requested changes
You should investigate why it is not possible to install aws-cli and fix

2020-09-16 16:58 UTC, Sudokamikaze commented
> You should investigate why it is not possible to install aws-cli and fix

It doesn't appear to be available in public repositories. It can be installed by official way: https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2.html

If it's OK, I'll implement it

2020-09-16 19:37 UTC, hors requested changes

2020-09-16 19:37 UTC, hors commented on IaC/ps80.cd/init.groovy.d/cloud.groovy
> -    sudo yum -y install java-1.8.0-openjdk git aws-cli || :
It should work for micro-amazon because it is Amazon Linux 2.

2020-09-17 09:19 UTC, hors approved these changes

2020-09-17 11:03 UTC, EvgeniyPatlan approved these changes

2020-09-17 18:54 UTC, Sudokamikaze commented
Jenkins ignores `|| true` so I had to move `git` out of one `yum install` in d9e93de 
/cc @EvgeniyPatlan @hors

2020-09-18 08:18 UTC, merged