Update Spot instance type of Jenkins workers in Oregon
Percona-Lab/jenkins-pipelines pull request #648
Opened 2020-11-18 18:28 UTC by Sudokamikaze

2020-11-18 18:29 UTC, EvgeniyPatlan approved these changes

2020-11-18 18:58 UTC, delgod requested changes

2020-11-18 18:58 UTC, delgod commented on IaC/ps80.cd/init.groovy.d/cloud.groovy
> -        ( typeMap[OSType].startsWith("c4") || typeMap[OSType].startsWith("m4") || typeMap[OSType].startsWith("c5") || typeMap[OSType].startsWith("m5") ), // boolean ebsOptimized
this change not needed

2020-11-18 18:58 UTC, delgod commented on IaC/pxb.cd/init.groovy.d/cloud.groovy
> +        ( typeMap[OSType].startsWith("c5") || typeMap[OSType].startsWith("m4") || typeMap[OSType].startsWith("c5") || typeMap[OSType].startsWith("m5") ), // boolean ebsOptimized
this change not needed

2020-11-19 08:11 UTC, delgod approved these changes

2020-11-19 08:22 UTC, EvgeniyPatlan approved these changes

2020-11-19 08:22 UTC, Sudokamikaze commented
In last force-push I've updated pricemap for m5.2xlarge for PS8.0

2020-11-19 08:50 UTC, merged