ENG-969: Implement AWS ECR for our internal build images
Percona-Lab/jenkins-pipelines pull request #782
Opened 2021-02-03 15:48 UTC by Sudokamikaze

Link to prepare job:

2021-02-04 07:14 UTC, delgod requested changes
`./pxc/jenkins/pxc57-pipeline.groovy,./pxc/jenkins/pxc56-pipeline.groovy,./pxc/jenkins/pxc80-pipeline.groovy,./pxb/docker/pxb24-single-platform-run.groovy,./pxb/docker/pxb80-single-platform-run.groovy`  must do `docker login`.

reason: when docker image is downloaded using an AWS Account - traffic is free.
please see https://aws.amazon.com/ecr/pricing/

2021-02-04 07:14 UTC, delgod commented on IaC/JenkinsImagesECR.yml
> +          Value: jenkins-ecr-readwriteuser
please ```suggestion
          Value: jenkins-ps-ecr
```

2021-02-04 07:14 UTC, delgod commented on pxc/jenkins/prepare-pxc-build-docker.yml
> +                        git poll: true, branch: 'ENG-969', url: 'https://github.com/Sudokamikaze/jenkins-pipelines'
please use our repo

2021-02-04 07:14 UTC, delgod commented on pxc/jenkins/prepare-pxc-build-docker.yml
> +                        docker login -u AWS -p \$ECR_TEMP_PASS public.ecr.aws/e7j3v3n0
more secure command (password not shown in the logs)

```
aws ecr-public get-login-password --region us-east-1 \
    | docker login --username AWS --password-stdin public.ecr.aws/e7j3v3n0
```

2021-02-04 08:15 UTC, Sudokamikaze commented on IaC/JenkinsImagesECR.yml
> +          - "x86-64"
This resource type can't be tagged: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-publicrepository.html

You're viewing wrong doc, ecr and ecr-public are different resources

2021-02-04 08:15 UTC, Sudokamikaze commented on pxc/jenkins/prepare-pxc-build-docker.yml
> +                        git poll: true, branch: 'ENG-969', url: 'https://github.com/Sudokamikaze/jenkins-pipelines'
Will be implemented before merge

2021-02-04 08:33 UTC, Sudokamikaze commented on IaC/JenkinsImagesECR.yml
> +          - "x86-64"
Also, it is not possible to add tags via Web GUI and via CLI, there's no such property

2021-02-04 15:44 UTC, delgod requested changes

2021-02-04 15:44 UTC, delgod commented on IaC/JenkinsImagesECR.yml
> +      UserName: "ECRROUser"
please it is critical to be able to identify resources from the name
```suggestion
          Value: jenkins-ps-ecr
      UserName: "jenkins-ps-ecr"
```

2021-02-05 14:22 UTC, delgod requested changes

2021-02-05 14:22 UTC, delgod commented on pxc/jenkins/pxc56-pipeline.groovy
> +							aws ecr-public get-login-password --region us-east-1 | docker login -u AWS --password-stdin public.ecr.aws/e7j3v3n0
wrong tabulation?

2021-02-05 14:22 UTC, delgod commented on pxc/jenkins/pxc57-pipeline.groovy
> -                        sh '''
why this line changed?

2021-02-05 14:22 UTC, delgod commented on pxc/jenkins/qa-pxc57-pipeline.groovy
> -                            sh '''
why it is changed?

2021-02-05 14:22 UTC, delgod commented on pxc/jenkins/qa-pxc57-pipeline.groovy
> +
wrong tabulation?

2021-02-05 14:34 UTC, Sudokamikaze commented on pxc/jenkins/pxc56-pipeline.groovy
> +							aws ecr-public get-login-password --region us-east-1 | docker login -u AWS --password-stdin public.ecr.aws/e7j3v3n0
Corrected

2021-02-05 14:34 UTC, Sudokamikaze commented on pxc/jenkins/pxc57-pipeline.groovy
> -                        sh '''
Corrected

2021-02-05 14:35 UTC, Sudokamikaze commented on pxc/jenkins/qa-pxc57-pipeline.groovy
> -                            sh '''
Corrected

2021-02-05 14:35 UTC, Sudokamikaze commented on pxc/jenkins/qa-pxc57-pipeline.groovy
> +
Corrected

2021-02-10 15:52 UTC, delgod approved these changes

2021-02-11 11:55 UTC, EvgeniyPatlan approved these changes

2021-02-11 22:52 UTC, merged